on:
    push:
        branches:
            - master
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
jobs:
    Inflate:
        runs-on: ubuntu-latest
        steps:
            - name: Get mod repo
              uses: actions/checkout@v3
            - name: Test meta-netkans
              uses: KSP-CKAN/xKAN-meta_testing@master
              with:
                  pull request url: ${{ github.event.pull_request.url }}
